[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Chrysanthemum Lovelace <chryslovelace@gmail.com>"]
edition = "2018"

[dependencies]
either = "1.6.1"
itertools = "0.9.0"
lazy_static = "1.4.0"
regex = "1.4.2"
